spring.application.name=soilpatrol-api
# Supabase PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?user=postgres.sdbjudcvufxxqdhuzdyj&password=$1n7s0s6B0B4911
spring.datasource.driver-class-name=org.postgresql.Driver
supabase.url=https://sdbjudcvufxxqdhuzdyj.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkYmp1ZGN2dWZ4eHFkaHV6ZHlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0NjIzNjQsImV4cCI6MjA5MTAzODM2NH0.QNLqodj0iQvYXpdyjU0ngIFwjsj6Z42hd0Os39Oa5ew
# JPA & Hibernate Settings
# CRITICAL: Set this to 'validate' or 'none'.
# Since we already built the tables in Supabase, we do NOT want Hibernate overwriting them.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

brain.url=https://soilpatrol-brain.onrender.com